# Generated by Django 6.0.7 on 2026-07-19 19:41

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id_snapshot", models.UUIDField()),
            ],
        ),
        migrations.AddField(
            model_name="alertincident",
            name="resolved_by_check_in",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_incidents",
                to="core.checkin",
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="location_accuracy_meters",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="response_deadline_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkinprofile",
            name="is_paused",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="checkinprofile",
            name="paused_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="checkinprofile",
            name="interval_seconds",
            field=models.PositiveIntegerField(
                default=86400,
                validators=[
                    django.core.validators.MinValueValidator(3600),
                    django.core.validators.MaxValueValidator(604800),
                    core.models.validate_whole_minutes,
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="checkin",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("latitude__isnull", False),
                    ("location_accuracy_meters__isnull", True),
                    _connector="OR",
                ),
                name="checkin_accuracy_requires_coordinates",
            ),
        ),
        migrations.AddConstraint(
            model_name="checkinprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("interval_seconds__gte", 3600), ("interval_seconds__lte", 604800)
                ),
                name="profile_interval_1h_7d",
            ),
        ),
        migrations.AddConstraint(
            model_name="checkinprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_paused", True), ("paused_until__isnull", True), _connector="OR"
                ),
                name="profile_pause_until_requires_pause",
            ),
        ),
        migrations.AddField(
            model_name="alertrecipient",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to="core.alertincident",
            ),
        ),
        migrations.AddField(
            model_name="alertrecipient",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alert_recipient_snapshots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="alertrecipient",
            constraint=models.UniqueConstraint(
                fields=("incident", "user_id_snapshot"), name="unique_alert_recipient_snapshot"
            ),
        ),
    ]
