# Generated by Django 6.0.7 on 2026-07-19 19:42

import django.db.models.functions.math
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alertrecipient_alertincident_resolved_by_check_in_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="checkinprofile",
            name="profile_interval_1h_7d",
        ),
        migrations.AddConstraint(
            model_name="checkinprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("interval_seconds__gte", 3600),
                    ("interval_seconds__lte", 604800),
                    django.db.models.lookups.Exact(
                        django.db.models.functions.math.Mod("interval_seconds", 60), 0
                    ),
                ),
                name="profile_interval_whole_minutes_1h_7d",
            ),
        ),
    ]
