# Generated by Django 6.0.7 on 2026-07-19 20:24

import hashlib

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def snapshot_existing_deliveries(apps, schema_editor):
    DeliveryAttempt = apps.get_model("core", "DeliveryAttempt")
    OutboxEvent = apps.get_model("core", "OutboxEvent")
    for delivery in DeliveryAttempt.objects.select_related("device").iterator():
        device = delivery.device
        if device is not None:
            delivery.device_id_snapshot = device.id
            delivery.destination_token_hash = hashlib.sha256(
                device.expo_push_token.encode()
            ).hexdigest()
            delivery.platform_snapshot = device.platform
        delivery.outbox_event = (
            OutboxEvent.objects.filter(
                aggregate_id=delivery.incident_id,
                event_type__in=["alert.opened", "alert.retry"],
            )
            .order_by("created_at")
            .first()
        )
        delivery.save(
            update_fields=[
                "device_id_snapshot",
                "destination_token_hash",
                "platform_snapshot",
                "outbox_event",
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_checkinprofile_profile_interval_1h_7d_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerHeartbeat",
            fields=[
                ("worker_name", models.CharField(max_length=80, primary_key=True, serialize=False)),
                (
                    "last_seen_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="deliveryattempt",
            name="unique_delivery_attempt",
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="destination_token_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="device_id_snapshot",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="outbox_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_attempts",
                to="core.outboxevent",
            ),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="platform_snapshot",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.RunPython(snapshot_existing_deliveries, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="deliveryattempt",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="core.pushdevice",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("ticket_received", "Ticket received"),
                    ("receipt_processing", "Receipt processing"),
                    ("delivered", "Delivered"),
                    ("retryable_failure", "Retryable failure"),
                    ("permanent_failure", "Permanent failure"),
                    ("dead_letter", "Dead letter"),
                ],
                default="queued",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("device_id_snapshot__isnull", False), ("outbox_event__isnull", False)
                ),
                fields=("outbox_event", "device_id_snapshot", "attempt_number"),
                name="unique_event_device_delivery_attempt",
            ),
        ),
    ]
