# Generated by Django 6.0.7 on 2026-07-19 21:32

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_workerheartbeat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("event_type", models.CharField(db_index=True, editable=False, max_length=80)),
                (
                    "actor_kind",
                    models.CharField(
                        choices=[("user", "User"), ("system", "System")],
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("aggregate_type", models.CharField(db_index=True, editable=False, max_length=80)),
                ("aggregate_id", models.UUIDField(db_index=True, editable=False)),
                ("metadata", models.JSONField(blank=True, default=dict, editable=False)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["aggregate_type", "aggregate_id", "occurred_at"],
                        name="core_audite_aggrega_e196e5_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="alertincident",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("profile",),
                name="unique_open_incident_per_profile",
            ),
        ),
    ]
