# Generated by Django 6.0.7 on 2026-07-19 21:51

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower
from django.utils import timezone


def verify_legacy_email_uniqueness_and_backfill(apps, schema_editor):
    user_model = apps.get_model("core", "User")
    duplicate_count = (
        user_model.objects.annotate(normalized_email=Lower("email"))
        .values("normalized_email")
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
        .count()
    )
    if duplicate_count:
        raise RuntimeError(
            "Case-insensitive duplicate user e-mails must be resolved before migration 0006."
        )
    user_model.objects.filter(email_verified_at__isnull=True).update(
        email_verified_at=timezone.now()
    )


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0005_auditevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "last_delivery_requested_at",
                    models.DateTimeField(default=timezone.now),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            verify_legacy_email_uniqueness_and_backfill,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="unique_user_email_case_insensitive",
            ),
        ),
        migrations.AddField(
            model_name="emailverificationchallenge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_verification_challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="emailverificationchallenge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cancelled_at__isnull", True), ("used_at__isnull", True)),
                fields=("user",),
                name="unique_active_email_verification",
            ),
        ),
    ]
