# Generated by Django 6.0.7 on 2026-07-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_email_verification"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="checkinprofile",
            name="unique_profile_name_per_owner",
        ),
        migrations.AddField(
            model_name="checkin",
            name="submitted_from_queue",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="checkinprofile",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="checkinprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("owner", "name"),
                name="unique_active_profile_name_per_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="checkinprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("archived_at__isnull", True),
                    models.Q(
                        ("enabled", False),
                        ("is_paused", True),
                        ("paused_until__isnull", True),
                        ("next_deadline_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="archived_profile_is_inert",
            ),
        ),
    ]
