# Generated by Django 6.0.7 on 2026-07-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_profile_archive_and_queue_provenance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("ticket_received", "Ticket received"),
                    ("receipt_processing", "Receipt processing"),
                    ("delivered", "Legacy provider accepted"),
                    ("provider_accepted", "Accepted by APNs/FCM"),
                    ("retryable_failure", "Retryable failure"),
                    ("permanent_failure", "Permanent failure"),
                    ("dead_letter", "Dead letter"),
                ],
                default="queued",
                max_length=32,
            ),
        ),
    ]
