# Generated by Django 6.0.7 on 2026-07-20 12:20

from django.db import migrations, models


def rename_delivered_to_provider_accepted(apps, schema_editor):
    delivery_attempt = apps.get_model("core", "DeliveryAttempt")
    delivery_attempt.objects.filter(status="delivered").update(status="provider_accepted")


def restore_legacy_delivered_status(apps, schema_editor):
    delivery_attempt = apps.get_model("core", "DeliveryAttempt")
    delivery_attempt.objects.filter(status="provider_accepted").update(status="delivered")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_profile_archive_and_queue_provenance"),
    ]

    operations = [
        migrations.RunPython(
            rename_delivered_to_provider_accepted,
            reverse_code=restore_legacy_delivered_status,
        ),
        migrations.AlterField(
            model_name="deliveryattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("ticket_received", "Ticket received"),
                    ("receipt_processing", "Receipt processing"),
                    ("provider_accepted", "Accepted by APNs/FCM"),
                    ("retryable_failure", "Retryable failure"),
                    ("permanent_failure", "Permanent failure"),
                    ("dead_letter", "Dead letter"),
                ],
                default="queued",
                max_length=32,
            ),
        ),
    ]
